### ISSUE TITLE
What is the difference between Voxel2D_hie Voxel2D Voxel2D_sprase

### ISSUE THREAD

**Issue by daichengqian** [RIVeR-Lab/stereovoxelnet#11]
i'm runing visualize_hie.py with model voxel.ckpt, it looks very well,
but when i tring test.py, Doesn't look like a match， the pretrained models maybe Voxel2D_hie
so how can i runing Voxel2D model, and what's the differenc between Voxel2D_hie Voxel2D Voxel2D_sprase
thank you

**Comment by lhy0807** [comment]
Thanks for the question. Sorry for the confusion. Voxel2D refers to the "Straight" method in [Table II](https://arxiv.org/abs/2209.08459). Voxel2D_hie refers to the "Dense" method, and Voxel2D_sparse refers to the "Sparse-Pred" method. We provide the checkpoint for Voxel2D_hie as it has the best performance.

**Comment by LOUYWEI** [comment]
@lhy0807 Hello, I have encountered a similar issue. I used your training code to train a **voxel2d** and **voxel2d_hie** on the DS dataset. However, when executing `test. py,` I received an error message for **cloud_pred**. Is there anything I need to pay attention to and modify? The **voxel2d_hie** that I trained myself can run `visualize_hie. py` normally. Similarly, using the **voxel.ckpt** file you provided to run `test. py`, I modified `from models. Voxel2D_hie import Voxel2D`, but still showed the  error message of **cloud_pred**.

**Comment by lhy0807** [comment]
Thanks for the question. Could you provide the error message you received? I can take a look on that

**Comment by LOUYWEI** [comment]
> Thanks for the question. Could you provide the error message you received? I can take a look on that

@lhy0807 , Thank you for your response

1. when i use the `voxel.ckpt` file you provided to run `test. py`, I only modified: `from models. Voxel2D_hie import Voxel2D`, but some error like:

```
  0%|          | 0/96 [00:00<?, ?it/s]2025-05-06 17:16:34 __main__[8209] WARNING Something bad happended Traceback (most recent call last):
  File "/home/lyw/code/stereovoxelnet/scripts/net/test.py", line 93, in <module>
    cloud_pred = np.asarray([(pt-offsets)*VOXEL_SIZE for pt in xyz_pred.T])
  File "/home/lyw/code/stereovoxelnet/scripts/net/test.py", line 93, in <listcomp>
    cloud_pred = np.asarray([(pt-offsets)*VOXEL_SIZE for pt in xyz_pred.T])
ValueError: operands could not be broadcast together with shapes (4,) (3,)

  0%|          | 0/96 [00:02<?, ?it/s]
Traceback (most recent call last):
  File "/home/lyw/code/stereovoxelnet/scripts/net/test.py", line 93, in <module>
    cloud_pred = np.asarray([(pt-offsets)*VOXEL_SIZE for pt in xyz_pred.T])
  File "/home/lyw/code/stereovoxelnet/scripts/net/test.py", line 93, in <listcomp>
    cloud_pred = np.asarray([(pt-offsets)*VOXEL_SIZE for pt in xyz_pred.T])
ValueError: operands could not be broadcast together with shapes (4,) (3,)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lyw/code/stereovoxelnet/scripts/net/test.py", line 112, in <module>
    logger.warning(f"cloud_pred shape {cloud_pred.shape}, cloud_np_gt shape {cloud_np_gt.shape}")
NameError: name 'cloud_pred' is not defined
```

2. in addition, i used your training code to train a `voxel2d` model on the DS dataset(I only used data from one sequence in the dataset), but some error like:
```
__main__[7505] WARNING cloud_pred shape (0,), cloud_np_gt shape (518, 3)
CD is 37.55004119873047, IoU is 0.07818399228568736, Invalid Sample 0 out of 1536 @ 0.0%:  16%|█▌        | 15/96 [00:08<00:30,  2.63it/s]2025-05-06 17:05:15 tjsiasun __main__[7505] WARNING Something bad happended Traceback (most recent call last):
  File "/home/lyw/code/stereovoxelnet/scripts/net/test.py", line 105, in <module>
    cd = chamfer_distance(torch.Tensor(np.expand_dims(cloud_pred,0)), torch.Tensor(np.expand_dims(cloud_np_gt,0)))[0]
  File "/home/lyw/miniconda3/envs/ovm/lib/python3.8/site-packages/pytorch3d/loss/chamfer.py", line 121, in chamfer_distance
    x, x_lengths, x_normals = _handle_pointcloud_input(x, x_lengths, x_normals)
  File "/home/lyw/miniconda3/envs/ovm/lib/python3.8/site-packages/pytorch3d/loss/chamfer.py", line 49, in _handle_pointcloud_input
    raise ValueError("Expected points to be of shape (N, P, D)")
ValueError: Expected points to be of shape (N, P, D)

__main__[7505] WARNING cloud_pred shape (0,), cloud_np_gt shape (593, 3)
CD is 35.84822463989258, IoU is 0.07995094832607132, Invalid Sample 0 out of 1536 @ 0.0%:  17%|█▋        | 16/96 [00:08<00:30,  2.65it/s]2025-05-06 17:05:15 tjsiasun __main__[7505] WARNING Something bad happended Traceback (most recent call last):
  File "/home/lyw/code/stereovoxelnet/scripts/net/test.py", line 105, in <module>
    cd = chamfer_distance(torch.Tensor(np.expand_dims(cloud_pred,0)), torch.Tensor(np.expand_dims(cloud_np_gt,0)))[0]
  File "/home/lyw/miniconda3/envs/ovm/lib/python3.8/site-packages/pytorch3d/loss/chamfer.py", line 121, in chamfer_distance
    x, x_lengths, x_normals = _handle_pointcloud_input(x, x_lengths, x_normals)
  File "/home/lyw/miniconda3/envs/ovm/lib/python3.8/site-packages/pytorch3d/loss/chamfer.py", line 49, in _handle_pointcloud_input
    raise ValueError("Expected points to be of shape (N, P, D)")
ValueError: Expected points to be of shape (N, P, D)
```
I haven't modified any other content in the code yet. Did you encounter such a problem during the experiment?
